### ISSUE TITLE
Can't multiply torch.tensor and gurobi.Var

### ISSUE THREAD

**Issue by dythebs** [oval-group/PLNN-verification#1]
./tools/pytorch2nnet.py ./planet/benchmarks/collisionDetection/reluBenchmark0.00517892837524s_UNSAT.rlv ./ReluplexCav2017/benchmarks//collisionDetectionNNet/reluBenchmark0.00517892837524s_UNSAT.nnet
Traceback (most recent call last):
  File "./tools/rlv_2_nnet.py", line 26, in <module>
    main()
  File "./tools/rlv_2_nnet.py", line 23, in main
    dump_nnet(args.nnet_outfile, all_layers, domain)
  File "/home/yang/PLNN-verification-master/venv/lib/python3.6/site-packages/PLNN_verification-0.0.1.dev1-py3.6.egg/plnn/model.py", line 750, in dump_nnet
  File "/home/yang/PLNN-verification-master/venv/lib/python3.6/site-packages/PLNN_verification-0.0.1.dev1-py3.6.egg/plnn/model.py", line 560, in reluify_maxpool
  File "/home/yang/PLNN-verification-master/venv/lib/python3.6/site-packages/PLNN_verification-0.0.1.dev1-py3.6.egg/plnn/network_linear_approximation.py", line 140, in define_linear_approximation
TypeError: mul() received an invalid combination of arguments - got (Var), but expected one of:
 * (Tensor other)
      didn't match because some of the arguments have invalid types: (Var)
 * (float other)
      didn't match because some of the arguments have invalid types: (Var)

![image](https://user-images.githubusercontent.com/37578699/42923426-f853b284-8b57-11e8-9698-de04c7678556.png)

**Comment by bunelr** [comment]
Hello,
Could you try to run things with an older version of pytorch? (Prior to 0.4)
I have had several reports of the code not working with the latest version, due to the merge between Tensors and Variables, but haven't had time to fix it yet.

Can you try downgrading pytorch version to see if it resolves the problem?

**Comment by dythebs** [comment]
OK，I try to install 0.3.1 and it works！Thanks！

**Comment by bunelr** [comment]
Sorry about this, I'll try to fix this as soon as possible.
